name: Terraform Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment, either dev, test, or prod"
        required: true
      region:
        description: "Region for deployment"
        required: true
      assume_role:
        description: "ARN of the role for GitHub Actions to assume"
        required: true
      account_id:
        description: "Current AWS Account ID"
        required: true

env:
  # When triggered by push, github.event.inputs is empty, so we use the defaults.
  TF_VAR_environment: ${{ github.event.inputs.environment || 'dev' }}
  TF_VAR_region: ${{ github.event.inputs.region || 'eu-west-2' }}
  TF_VAR_assume_role: ${{ github.event.inputs.assume_role || 'arn:aws:iam::559050248035:role/OIDCRole' }}
  TF_VAR_account_id: ${{ github.event.inputs.account_id || '559050248035' }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ github.event.inputs.assume_role || 'arn:aws:iam::559050248035:role/OIDCRole' }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ github.event.inputs.region || 'eu-west-2' }}

      - name: STS Get Caller Identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ github.event.inputs.account_id || '559050248035' }}-${{ github.event.inputs.region || 'eu-west-2' }}-backend-infra-tf-yt" \
            -backend-config="region=${{ github.event.inputs.region || 'eu-west-2' }}" \
            -backend-config="dynamodb_table=${{ github.event.inputs.account_id || '559050248035' }}-${{ github.event.inputs.region || 'eu-west-2' }}-backend-infra-tf-yt-lock" \
            -backend-config="key=terraform/state.tfstate"

      - name: Terraform Plan
        run: terraform plan -var="environment=${{ github.event.inputs.environment || 'dev' }}" -var="region=${{ github.event.inputs.region || 'eu-west-2' }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="environment=${{ github.event.inputs.environment || 'dev' }}" -var="region=${{ github.event.inputs.region || 'eu-west-2' }}"
