name: Terraform Deployment

on:
  push:
    branches: [ "main" ]

env:
    REGION: "eu-west-2"
    ENVIRONMENT: "dev"
    TARGET_ACCOUNT: "${{ fromJson('{\"prod\": \"864981715246\", \"dev\": \"559050248035\", \"staging\": \"890742571404\"}')[github.event.inputs.environment] }}"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: "arn:aws:iam::${{ env.OIDC_ROLE_ARN }}:role/OIDCRole"
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.REGION }}

      - name: STS Get Caller Identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.TARGET_ACCOUNT }}-${{ env.REGION }}-backend-infra-tf-yt" \
            -backend-config="region=${{ env.REGION }}" \
            -backend-config="dynamodb_table=${{ env.TARGET_ACCOUNT }}-${{ env.REGION }}-backend-infra-tf-yt-lock" \
            -backend-config="key=terraform/state.tfstate"

      - name: Terraform Plan
        run: terraform plan -var="environment=${{ env.ENVIRONMENT }}" -var="region=${{ env.REGION }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="environment=${{ env.ENVIRONMENT }}" -var="region=${{ env.REGION }}"
